version: '3.4'

services:
  xiaperls:
    image: xiaperls
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
         - NODE_BUILD_ENV=production
    env_file:
      - ./.env
    command: ["npm", "start"]

