version: '3.4'

services:
  xiaperls:
    image: xiaperls
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
         - NODE_BUILD_ENV=production=false
    env_file:
      - ./.env
    volumes:
      - ./dist:/usr/src/app/dist
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 9229:9229
    command: ["npm", "run", "debug"]
