name: NodeJS with Mocha

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.3
      uses: actions/setup-node@v2
      with:
        node-version: 16.3

    - name: Build
      run: |
        npm install
        npm code-coverage
