name: 'Test Report'
on:
  workflow_run:
    workflows: ['NodeJS with Mocha']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Mocha Tests
        path: 'test-results.json'
        reporter: mocha-json
